import { UserRoleContextProvider } from '../context/role-info';
import Providers from '../utils/provider';

import './global.css';

export const metadata = {
    title: 'Welcome to admin',
    description: 'Generated by create-nx-workspace',
}; // TODO HEAD not work
// TODO https://github.com/Skyleen77/next-nprogress-bar

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <UserRoleContextProvider>{children}</UserRoleContextProvider>
                </Providers>
            </body>
        </html>
    );
};

export default RootLayout;
