import './global.css';

export const metadata = {
    title: 'Welcome to nest-test',
    description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body>
                <h1> the root layout</h1>
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
