import Providers from '@frontend/utils/provider';
import { dir } from 'i18next';
import { UserRoleContextProvider } from '@frontend/context/role-info';

import { languages } from '../i18n/settings';

import './global.css';

interface StaticParams {
    lng: string;
}
export async function generateStaticParams(): Promise<StaticParams[]> {
    return languages.map((lng: string) => ({ lng }));
}
interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        lng: string;
    };
}

// export const metadata = {
//     title: 'Welcome to admin',
//     description: 'Generated by create-nx-workspace',
// }; // TODO HEAD not work, next video

const RootLayout = async ({ children, params: { lng } }: RootLayoutProps) => {
    return (
        <html lang={lng} dir={dir(lng)}>
            <body>
                <Providers>
                    <UserRoleContextProvider>{children}</UserRoleContextProvider>
                </Providers>
            </body>
        </html>
    );
};

export default RootLayout;
